feat(Password): made a new input password
gravity-ui/components pull request #108
Opened 2023-10-09 11:20 UTC by NasgulNexus

2023-10-09 11:26 UTC, personaljs commented on src/components/Password/Password.tsx
> +import _ from 'lodash';
зачем тут lodash?

2023-10-09 12:33 UTC, amje requested changes

2023-10-09 12:33 UTC, amje commented on src/components/Password/Password.tsx
> +export const Password: React.FC<PasswordProps> = (props) => {
`Password` -> `PasswordInput`

2023-10-09 12:33 UTC, amje commented on src/components/Password/Password.tsx
> +        showCopyButton?: boolean;
`showVisibilityButton` should also be in the props

2023-10-09 12:33 UTC, amje commented on src/components/Password/Password.tsx
> +            <div className={b()}>
Root class is assigned to the extra content, not the TextInput

2023-10-09 12:33 UTC, amje commented on src/components/Password/Password.tsx
> +    Omit<TextInputProps, 'rightContent' | 'type'> & {
Why omit `rightContent`? We can prepend it to buttons

2023-10-11 13:00 UTC, amje commented on src/components/PasswordInput/PasswordInput.tsx
> +                        size="s"
We should use different sizes for each TextInput size

2023-10-11 13:02 UTC, amje commented on src/components/PasswordInput/PasswordInput.tsx
> +                        view="flat-secondary"
aria-label prop would be nice here with the texts: `Show password/Hide password`

2023-10-11 13:06 UTC, amje requested changes

2023-10-11 13:06 UTC, amje commented on src/components/PasswordInput/PasswordInput.tsx
> +            className={b('input', className)}
That's not the input's className, you should pass it to the `controlProps` prop

2023-10-16 10:52 UTC, amje requested changes

2023-10-16 10:52 UTC, amje commented on src/components/PasswordInput/PasswordInput.tsx
> +        hasTooltip?: boolean;
I would pick separate names here, `hasCopyTooltip` and `hasRevealTooltip`

2023-10-16 10:52 UTC, amje commented on src/components/PasswordInput/PasswordInput.tsx
> +                        size={16}
We should map input size to button size

2023-10-16 10:52 UTC, amje commented on src/components/PasswordInput/PasswordInput.tsx
> +                            size={size}
TextInput size !== Button size, take a look at clear button, maybe reuse this [logic](https://github.com/gravity-ui/uikit/blob/e9aff632b924307e7700e76855ba15abc905be3b/src/components/controls/common/ClearButton/ClearButton.tsx#L23) here as well

2023-10-16 10:52 UTC, amje commented on src/components/PasswordInput/PasswordInput.tsx
> +                className: b(),
Now it's an opposite, you're passing root className (`b()`) to the control node

2023-10-26 14:34 UTC, personaljs commented on src/components/PasswordInput/__stories__/PasswordInput.stories.tsx
> +            <Button onClick={generateRandomValue} className={b('button-generate-random-value')}>
давай добавим showCopyButton={true} showRevealButton={true}

2023-10-31 10:45 UTC, amje requested changes

2023-10-31 10:45 UTC, amje commented on src/components/PasswordInput/PasswordInput.tsx
> +                ...controlProps,
Spread should be before the className, otherwise it would be overwritten by the controlProps

2023-10-31 19:52 UTC, amje approved these changes

2023-11-01 08:40 UTC, merged