fix(InfiniteScroll): fixed the double `onActivate` in the `InfiniteScroll` component
gravity-ui/components pull request #81
Opened 2023-07-24 13:08 UTC by Ruminat

Issue: https://github.com/gravity-ui/components/issues/80
Solution: added a small delay after the first `onActivate` so that the second (wrong) one won't be called.

2023-07-24 13:36 UTC, korvin89 requested changes
Why is it called multiple times? Apparently, you want to fix the consequence of the problem, not the problem itself.

2023-07-24 14:03 UTC, Ruminat commented
It's `IntersectionObserver` which changes `isBottomVisible`, so I'm not sure we can do anything about that

2023-07-24 14:18 UTC, Ruminat commented
Or maybe we can do another check (if the `intersector` is visible) with the `isActive` check
I will investigate more

2023-07-25 09:55 UTC, korvin89 approved these changes

2023-07-25 10:43 UTC, merged