feat: update linting plugins
gravity-ui/components pull request #84
Opened 2023-07-31 08:44 UTC by KirillDyachkovskiy

2023-07-31 09:14 UTC, Marginy605 approved these changes

2023-07-31 09:21 UTC, korvin89 requested changes
We have our own rules here https://github.com/gravity-ui/eslint-config

2023-07-31 09:23 UTC, NikitaCG requested changes

2023-07-31 09:23 UTC, NikitaCG commented on .eslintrc
> +        "import/order": [
Don't you want to add it here https://github.com/gravity-ui/eslint-config ? If someone wants to set the same rules for themselves, then they just import them into their project

2023-08-01 12:35 UTC, korvin89 approved these changes

2023-08-01 12:37 UTC, NikitaCG approved these changes

2023-08-01 14:39 UTC, Ruminat approved these changes

2023-08-01 14:40 UTC, merged